#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: "Miri Morgulis Lab Notebook â€“ Mass Lab"

# Short bio or description (displayed in the header)
description: "Postdoctoral researcher"

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: "https://avatars.githubusercontent.com/u/76209416?s=200&v=4"

#
# Flags below are optional
#

footer-links:
  dribbble:
  email: mmorguli@campus.haifa.ac.il
  facebook:
  flickr:
  github: MiriMorgulis
  instagram:
  linkedin: miri-morgulis
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:

# Enter your Disqus shortname
disqus:

# Google Analytics tracking code
google_analytics:

# Your USER site URL (NOT the project path!)
url: "https://mirimorgulis.github.io"

# Your project folder
baseurl: "/Open_Lab_Notebook_Mass_Lab"

#
# You don't need to change anything below
#

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
